### ISSUE TITLE
Misused Docker container

### ISSUE THREAD

**Issue by icedevml** [enisaeu/ecsc-gameboard#16]
Hello guys,

from your `Dockerfile` I see that you are setting up the whole Debian inside Docker and you have MySQL, Apache2 and even a sshd server in a single container.

https://github.com/enisaeu/ecsc-gameboard/blob/master/Dockerfile#L7
https://github.com/enisaeu/ecsc-gameboard/blob/master/setup.sh#L47

This is **NOT** how Docker is intended to be used. From official docs:

> It is generally recommended that you separate areas of concern by using one service per container. That service may fork into multiple processes (for example, Apache web server starts multiple worker processes). It’s ok to have multiple processes, but to get the most benefit out of Docker, avoid one container being responsible for multiple aspects of your overall application. You can connect multiple containers using user-defined networks and shared volumes.

**Comment by stamparm** [comment]
I don't see a problem here. There is a "general recommendation", while there is something called "platform". By searching for `LAMP `at https://hub.docker.com/search?q=lamp&type=image you'll get 2569 results. By searching for `Docker LAMP` on Google you'll get over 2 million results. Do you want to say that `LAMP` is not something that should be run inside a Docker container?

If you would like to split your `LAMP` platform into multiple "Docker" instances, be my guest. Otherwise, this whole issue doesn't make any sense

**Comment by stamparm** [comment]
Why would anybody sane raise an Issue to recommend an installation of a LAMP platform parts inside multiple Docker containers?!

Please, either have a constructive comment/Issue or don't raise it in the first place

**Comment by stamparm** [comment]
p.s. `setup.sh` is a general installation script. It doesn't have to be run "inside Docker"

**Comment by icedevml** [comment]
> Do you want to say that LAMP is not something that should be run inside a Docker container?

It is not something that should be run inside a **single** Docker container because these are multiple services, so you should use something like `docker-compose` in order to build your LAMP stack rather than write hacks. This also has possible impact on security.

**Comment by icedevml** [comment]
> p.s. `setup.sh` is a general installation script. It doesn't have to be run "inside Docker"

So I have to run this script on my host machine instead and let it mess with my system settings e.g. by changing my sshd settings to less secure? :confused: (My current setting is `PermitRootLogin no`)

https://github.com/enisaeu/ecsc-gameboard/blob/master/setup.sh#L47
```
sed -i 's/PermitRootLogin.*/PermitRootLogin without-password/g' /etc/ssh/sshd_config
```

Btw. when I type `docker lamp` into Google, first thing that appears is:

> sprintcube/docker-compose-lamp: A basic LAMP ... - GitHub
> A basic LAMP stack environment built **using Docker Compose**. - sprintcube/docker-compose-lamp.

and consists of separate containers which fullfil **Single Responsibility Principle**

**Comment by stamparm** [comment]
@icedevml So, basically you are just LARPing because of "security" or?

`So I have to run this script on my host machine instead and let it mess with my system settings` <- oh, come on. At https://github.com/enisaeu/ecsc-gameboard/#installation says `On fresh installation of Debian or Ubuntu OS`

Please, either propose something tangible or?

**Comment by stamparm** [comment]
`Messes up with my system by changing secure AllowOverride None to All for the whole Apache.` <- you are just trolling here

**Comment by stamparm** [comment]
One LAST comment. Whole installation part (i.e. `setup.sh`) is primary being done to run it on a fresh installed machine/platform. Docker installation file is here just to do everything the same, only inside the Docker container (i.e. everything up and running in easiest way possible). LARPing that "security" is bad because Apache and MySQL will be run inside the same Docker instance, while the majority of LAMP instances on the Internet are being run on same machines just make this whole "but security" arguments invalid.
