### ISSUE TITLE
Notification changes

### ISSUE THREAD

**Issue by bartusek27** [enisaeu/ecsc-gameboard#35]
Hello @stamparm @belmontemartin ,

we would like to make global notifications and announcements more visible and clear to all teams, that are made by the administrators.

**The outcome of this edit should be that notifications from admins will be more visible.**

We are proposing these options, where we're giving you the choice of picking at least one option to notify teams more efficiently:

### Options:
1. In the right corner where chat resides, we would suggest some kind of a flashing symbol, that could highlight the latest announcement. Highlighting/flashing should stop when someone from the team will "dismiss" the notification.
2. Using pop-up with grayed background with the predefined text. As soon as at least one of the members will dismiss the pop-up, it won't show again, but will be moved to a different, maybe whole new tab called "Admin Notifications".

### Nice to have:
Logging the dismissal of the notifications for admins. Something in the database should be sufficient but can be inside the frontend.

Reach out to me in case of any questions.

_Thanks,
Jiří from ECSC 2021 team_

**Comment by bartusek27** [comment]
Hello @stamparm,

what's the status on this issue? The date for us running the portal for the teams to test it out is closing on and we need to test the platform ourselves too.

Thank you and have a nice day!

**Comment by stamparm** [comment]
This part should be over. `Notifications` tab is being dash-bordered. I didn't want to introduce any animations or pop-ups as in previous years there were complaints on potential seizure attacks on introduced animations or flashing or similar

**Comment by liskaant** [comment]
Thank you @stamparm for implementing this. I agree that simple dash border si more than enough. However the problem is that the highlight should be presnet until user opens the notification tab.

I understand it is hrader to implement, however I can clearly imagine a situation, where user quickly clicks a link on a page after having it open in brackground for a while. In this case he will not notice the notification. The same applies to a situation where user was logged out when the notification was posted.

Would it be possible to add this?

Kind regards,
Antonin Liska

**Comment by stamparm** [comment]
@liskaant doable. so, i'll do that dashboard until open and let you know

**Comment by stamparm** [comment]
@liskaant with latest revision, your request should be implemented

**Comment by liskaant** [comment]
@stamparm Works well, thank you.
