### ISSUE TITLE
New Scoring types

### ISSUE THREAD

**Issue by bartusek27** [enisaeu/ecsc-gameboard#38]
Hello @stamparm @belmontemartin ,

we are proposing a new feature of changing the scoring method of the event. Since we want to use a dynamic scoring method, we need to change the way of how the platform awards the contestants. Because of the currently implemented static point scoring method, we propose that the platform should have a possibility to set the scoring method for the event.

- Platform should have a switch to choose between regular and dynamic scoring.
- If the dynamic scoring is enabled, inside the Admin section of the gameboard, there should be a tab called "Scoring", where you should be able to **a)** [NEEDED] set the points for each amount of solves per challenges that teams will get; **b)** [NICE TO HAVE] set the formula with parameters (amount of currently sent solves, number of teams or decay - the number of solves before the challenge will be at the minimum, maximum of points, minimal points).
- The commonly used formula is described e.g. https://github.com/CTFd/DynamicValueChallenge
- In option a) you need to check the number of teams competing and set a value of a challenge for each number of teams that have solved that challenge - meaning that if 1 team solves the challenge, they will receive e.g. 500 points. If some other team will manage to solve this same challenge too, the first team's score won't be 500 points, but only e.g. 485 points, the same as the second team.
- Inside the portal where are the graphs and tables of the score, it needs to be defined as only "Estimates" - since we are using dynamic scoring, the final amounts of the team's score is subject to change until the end of the event (or day, should be configurable).

Feel free to reach out to me in case of any questions.

Thanks,
Jiří from ECSC 2021 team

**Comment by stamparm** [comment]
1) For start, I am pro implementing the idea of CTFd dynamic value scoring. Also, I am for KISS solutions. Thus, I would just focus on the CTFd way or no way (as you say options), because from my own experience, if we'll complicate here too much, nobody would use either (dynamic scoring) option
2) Now, the trick question goes like this. Somebody has to choose one important thing (regarding the CTFd dynamic decaying options), because I can imagine lots of people that would nag in one or the other way. Whether there should be the global CTFd dynamic decaying options (e.g. decay factor and minimum points in terms of percentage) OR there should all those options be available in ALL tasks.

Personally, I am for global (CTFd formula) options, because that's KISS. If you all decide that you want all those options to appear per task, I'll implement that, BUT, I can imagine that people will find that as redundant in terms of filling all those values. For example, in such case, challenge "fillers" will need to additionally fill the "minimum value" for each task, because that's per task dependent. Also, filler will need to fill some decay factor value <- if you say here, fine, put some default value, then it should be also fine to just use some global options for all this

Anyhow, this is one of those requirements where I know that there will be protests in any case decided/implemented, because, AFAIR, two years ago there were like 20-30 people doing meetings just to determine if the dynamic scoring used (there was one custom made at that time) is properly being done (e.g. problems like these https://community.majorleaguecyber.org/t/ctf-dynamic-scoring-not-working/48)

**Comment by stamparm** [comment]
Hello @bartusek27 ,

what's the status on this issue? The date for you running the portal for the teams to test it out is closing on and you need to test the platform too.

I've posted a question 27 days ago and you haven't replied to it.

Thank you and have a nice day!

**Comment by bartusek27** [comment]
Hello @stamparm,

as far as I see, you kinda already decided what to implement - and to be honest, it makes sense to make it as simple as possible, so it can be used by more events in the future. If the dynamic scoring is already implemented according to CTFd rules (if I remember correctly, dynamic scoring is already implemented into the platform), then my colleague that is responsible for running the game portal at the ECSC will change the currently hardcoded formula to our own, which we have already agreed to.

What is only left here is to know when we can fork this repo to make the necessary changes. My point is that because we don't have the status for other changes (that might not be here as issues but you've got them from @belmontemartin), we don't know what commit of yours shall be your final one before ECSC. Since we are obliged to have the portal already running by 15th August, we would like to have everything ready by Wednesday so we have enough time to prepare everything, including testing all changes and preparing some especially complicated challenges.

Thank you and have a nice day!
_Jiří from ECSC 2021 team_

**Comment by stamparm** [comment]
@bartusek27 @liskaant CTFd formula should be implemented days ago. Now, there are two global options available (if `Dynamic scoring` checkbox is turned on):

1) `Dynamic solve threshold:` - putting (e.g.) 20 here means that the `CTFd` specific decay will work for first 20 solves, after which point, decay will reach its maximum decay value
2) `Dynamic maximum decay (%):` - putting (reasonable) 50% here would mean that the decay won't go over the 50% of the starting/maximum points of the challenge itself

![1](https://user-images.githubusercontent.com/921555/127926734-610b8b4b-9ce3-46fb-90a3-ae5ebab514c1.png)
